name: Run Tests
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  check-and-test:
    name: Check and Test
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.4.0

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install NPM Packages
        run: npm ci

      - name: Install ubuntu credential store dependencies
        run: |
          sudo apt-get install libkrb5-dev
          sudo apt-get install xvfb
          sudo apt-get install dbus-x11
          sudo apt-get install libsecret-1-dev
          sudo apt-get install gnome-keyring
          sudo apt-get install libsecret-tools

      - name: Setup credential store for ubuntu
        run: |
          echo "activating dbus..."
          export "$(dbus-launch)"
          echo "activating gnome-keyring daemon..."
          echo "" | gnome-keyring-daemon --unlock
          gnome-keyring-daemon --start --daemonize --components=secrets
          export "$(echo "" | gnome-keyring-daemon -r -d --unlock)"
          echo "creating a test keychain record using \"secret-tool\" binary and then listing it..."
          echo -n "secret-tool-password-1" | secret-tool store --label=secret-tool-label-1 secret-tool-key-1 secret-tool-value-1
          secret-tool search secret-tool-key-1 secret-tool-value-1

      - name: Check and Test
        run: |
          npm run check
          npm run cover
          xvfb-run --auto-servernum npm run test:karma
